from __future__ import annotations
from typing import Protocol
from trading_agent.decision.schema import Decision


class BrokerClient(Protocol):
    name: str
    def get_equity(self) -> float: ...
    def get_daily_pnl(self) -> float: ...
    def get_positions(self) -> dict[str, float]: ...
    def get_market_data(self, symbol: str) -> dict[str, float]: ...
    def place_order(self, decision: Decision) -> dict[str, object]: ...
    def cancel_order(self, order_id: str) -> None: ...
